// 📦 masterData.js - ฐานข้อมูลสินค้าทั้งหมดของ HAUS IZAKAYA

export const MASTER_DATA = {
    // 🍳 โซนครัว (KITCHEN)
    KITCHEN: {
      "เนื้อสัตว์ อาหารทะเล (MEA01)": [
        { id: "MEA01-N001-77-S01", name: "หมูคุโรบุตะ", searchKey: "หมู คุโรบุตะ kurobuta pork", unit1: "แพ็ค", unit2: "", usage: 0 },
        { id: "MEA01-N002-77-S01", name: "ตับไก่", searchKey: "ตับไก่ chicken liver", unit1: "แพ็ค", unit2: "", usage: 0 },
        { id: "MEA01-N003-77-S01", name: "กึ๋นไก่", searchKey: "กึ๋นไก่ chicken gizzard", unit1: "แพ็ค", unit2: "", usage: 0 },
        { id: "MEA01-N004-77-S01", name: "สะโพกไก่", searchKey: "สะโพกไก่ chicken hip", unit1: "แพ็ค", unit2: "", usage: 0 },
        { id: "MEA01-N005-77-S01", name: "ปีกกลางไก่", searchKey: "ปีกกลางไก่ chicken wing", unit1: "แพ็ค", unit2: "", usage: 0 },
        { id: "MEA01-N006-77-S01", name: "เอ็นข้อไก่", searchKey: "เอ็นข้อไก่ chicken tendon", unit1: "แพ็ค", unit2: "", usage: 0 },
        { id: "MEA01-N007-77-S01", name: "หนังไก่", searchKey: "หนังไก่ chicken skin", unit1: "แพ็ค", unit2: "", usage: 0 },
        { id: "MEA01-N008-77-S01", name: "เต้าหู้ปลา", searchKey: "เต้าหู้ปลา fish tofu", unit1: "แพ็ค", unit2: "", usage: 0 },
        { id: "MEA01-N009-77-S01", name: "ปูอัดซาซิมิ", searchKey: "ปูอัด ซาซิมิ crab stick sashimi", unit1: "แพ็ค", unit2: "", usage: 0 },
        { id: "MEA01-N010-77-S01", name: "แมงกระพรุนจืด", searchKey: "แมงกระพรุน jellyfish", unit1: "แพ็ค", unit2: "", usage: 0 },
        { id: "MEA01-N011-66-S01", name: "เต้าหู้โมเมน", searchKey: "เต้าหู้โมเมน tofu momen", unit1: "กล่อง", unit2: "", usage: 0 },
        { id: "MEA01-N012-66-S01", name: "เต้าหู้คินุ", searchKey: "เต้าหู้คินุ tofu kinu", unit1: "กล่อง", unit2: "", usage: 0 },
        { id: "MEA01-N013-77-S01", name: "ปลาหมึก", searchKey: "ปลาหมึก squid", unit1: "แพ็ค", unit2: "", usage: 0 },
        { id: "MEA01-N014-33-S01", name: "ไข่ไก่", searchKey: "ไข่ไก่ egg", unit1: "แผง", unit2: "", usage: 0 },
        { id: "MEA01-N015-99-S02", name: "สันคอหมู", searchKey: "สันคอหมู pork neck", unit1: "กก.", unit2: "ขีด", usage: 0 },
        { id: "MEA01-N016-99-S02", name: "สันนอกหมู", searchKey: "สันนอกหมู pork loin", unit1: "กก.", unit2: "ขีด", usage: 0 },
        { id: "MEA01-N017-99-S02", name: "สามชั้น", searchKey: "สามชั้น pork belly", unit1: "กก.", unit2: "ขีด", usage: 0 },
        { id: "MEA01-N018-99-S02", name: "สามชั้นพันเห็ด", searchKey: "สามชั้นพันเห็ด bacon wrapped mushroom", unit1: "กก.", unit2: "ขีด", usage: 0 },
        { id: "MEA01-N019-99-S02", name: "หมูบด", searchKey: "หมูบด minced pork", unit1: "กก.", unit2: "ขีด", usage: 0 },
        { id: "MEA01-N020-99-S02", name: "มันหมู", searchKey: "มันหมู pork fat", unit1: "กก.", unit2: "ขีด", usage: 0 },
        { id: "MEA01-N021-77-S04", name: "ท้องแซลมอน", searchKey: "ท้องแซลมอน salmon belly", unit1: "แพ็ค", unit2: "", usage: 0 },
        { id: "MEA01-N022-77-S04", name: "ทาโกะวาซาบิ", searchKey: "ทาโกะวาซาบิ tako wasabi", unit1: "แพ็ค", unit2: "", usage: 0 },
        { id: "MEA01-N023-77-S04", name: "หมึกร้า", searchKey: "หมึกร้า shiokara", unit1: "แพ็ค", unit2: "", usage: 0 },
        { id: "MEA01-N024-77-S04", name: "ครีบปลากระเบน", searchKey: "ครีบปลากระเบน stingray fin", unit1: "แพ็ค", unit2: "", usage: 0 },
        { id: "MEA01-N025-77-S04", name: "กระดองปู", searchKey: "กระดองปู crab shell", unit1: "แพ็ค", unit2: "", usage: 0 },
        { id: "MEA01-N026-77-S04", name: "คานิ/ปูอัด", searchKey: "คานิ ปูอัด kani", unit1: "แพ็ค", unit2: "", usage: 0 },
        { id: "MEA01-N027-77-S04", name: "ปลาซาบะแช่แข็ง", searchKey: "ปลาซาบะ saba fish", unit1: "แพ็ค", unit2: "", usage: 0 },
        { id: "MEA01-N028-77-S04", name: "ทูน่า", searchKey: "ทูน่า tuna", unit1: "แพ็ค", unit2: "", usage: 0 },
        { id: "MEA01-N029-77-S04", name: "ไข่กุ้ง", searchKey: "ไข่กุ้ง shrimp roe", unit1: "แพ็ค", unit2: "", usage: 0 },
        { id: "MEA01-N030-77-S04", name: "ยำสาหร่าย", searchKey: "ยำสาหร่าย seaweed salad", unit1: "แพ็ค", unit2: "", usage: 0 },
        { id: "MEA01-N031-99-S04", name: "หมึกซาซิมิ", searchKey: "หมึกซาซิมิ squid sashimi", unit1: "กก.", unit2: "ขีด", usage: 0 },
        { id: "MEA01-N032-77-S04", name: "ปูอัดเสียบไม้", searchKey: "ปูอัดเสียบไม้ crab stick skewer", unit1: "แพ็ค", unit2: "", usage: 0 },
        { id: "MEA01-N033-77-S04", name: "ปลาไข่", searchKey: "ปลาไข่ shishamo", unit1: "แพ็ค", unit2: "", usage: 0 },
        { id: "MEA01-N034-77-S04", name: "หอยเชลล์", searchKey: "หอยเชลล์ scallop", unit1: "แพ็ค", unit2: "", usage: 0 },
        { id: "MEA01-N035-99-S04", name: "ฟัวกรา", searchKey: "ฟัวกรา foie gras", unit1: "กก.", unit2: "ขีด", usage: 0 },
        { id: "MEA01-N036-77-S04", name: "กุ้งหวาน", searchKey: "กุ้งหวาน sweet shrimp", unit1: "แพ็ค", unit2: "", usage: 0 },
        { id: "MEA01-N037-77-S04", name: "ปลาไหล", searchKey: "ปลาไหล unagi eel", unit1: "แพ็ค", unit2: "", usage: 0 },
        { id: "MEA01-N038-77-S04", name: "ไข่แซลมอน", searchKey: "ไข่แซลมอน salmon roe", unit1: "แพ็ค", unit2: "", usage: 0 },
        { id: "MEA01-N039-77-S04", name: "เอนกาวะ", searchKey: "เอนกาวะ engawa", unit1: "แพ็ค", unit2: "", usage: 0 },
        { id: "MEA01-N040-77-S04", name: "ไส้กรอกแดง", searchKey: "ไส้กรอกแดง red sausage", unit1: "แพ็ค", unit2: "", usage: 0 },
        { id: "MEA01-N041-77-S04", name: "ปลาเงิน", searchKey: "ปลาเงิน silver fish", unit1: "แพ็ค", unit2: "", usage: 0 },
        { id: "MEA01-N042-33-S04", name: "ปลาแซลมอน", searchKey: "ปลาแซลมอน salmon whole", unit1: "ตัว", unit2: "", usage: 0 }
      ],
      "ผัก ผลไม้ สมุนไพร (VEG01)": [
        { id: "VEG01-N001-77-S01", name: "มันหวาน", searchKey: "มันหวาน sweet potato", unit1: "แพ็ค", unit2: "", usage: 0 },
        { id: "VEG01-N002-77-S01", name: "ต้นหอมญี่ปุ่น", searchKey: "ต้นหอมญี่ปุ่น japanese bunching onion", unit1: "แพ็ค", unit2: "", usage: 0 },
        { id: "VEG01-N003-77-S01", name: "แตงกวาญี่ปุ่น", searchKey: "แตงกวาญี่ปุ่น japanese cucumber", unit1: "แพ็ค", unit2: "", usage: 0 },
        { id: "VEG01-N004-66-S01", name: "พาสเล่", searchKey: "พาสเล่ parsley", unit1: "กล่อง", unit2: "", usage: 0 },
        { id: "VEG01-N005-66-S01", name: "ดอกไม้กินได้", searchKey: "ดอกไม้กินได้ edible flower", unit1: "กล่อง", unit2: "", usage: 0 },
        { id: "VEG01-N006-77-S01", name: "เลม่อน", searchKey: "เลม่อน lemon", unit1: "แพ็ค", unit2: "", usage: 0 },
        { id: "VEG01-N007-77-S01", name: "เห็ดหอม", searchKey: "เห็ดหอม shiitake mushroom", unit1: "แพ็ค", unit2: "", usage: 0 },
        { id: "VEG01-N008-77-S01", name: "น้ำกระเทียมดอง", searchKey: "น้ำกระเทียมดอง pickled garlic", unit1: "แพ็ค", unit2: "", usage: 0 },
        { id: "VEG01-N009-77-S01", name: "เฟรนฟราย", searchKey: "เฟรนฟราย french fries", unit1: "แพ็ค", unit2: "", usage: 0 },
        { id: "VEG01-N010-88-S03", name: "รากผักชี", searchKey: "รากผักชี coriander root", unit1: "กรัม", unit2: "", usage: 0 },
        { id: "VEG01-N011-88-S03", name: "ขึ้นช่าย", searchKey: "ขึ้นช่าย celery", unit1: "กรัม", unit2: "", usage: 0 },
        { id: "VEG01-N012-88-S03", name: "ต้นหอม", searchKey: "ต้นหอม spring onion", unit1: "กรัม", unit2: "", usage: 0 },
        { id: "VEG01-N013-88-S03", name: "ผักชีใบเลื่อย", searchKey: "ผักชีใบเลื่อย sawtooth coriander", unit1: "กรัม", unit2: "", usage: 0 },
        { id: "VEG01-N014-88-S03", name: "กุยช่าย", searchKey: "กุยช่าย chives", unit1: "กรัม", unit2: "", usage: 0 },
        { id: "VEG01-N015-88-S03", name: "ตะไคร้", searchKey: "ตะไคร้ lemongrass", unit1: "กรัม", unit2: "", usage: 0 },
        { id: "VEG01-N016-33-S03", name: "หัวไชเท้า", searchKey: "หัวไชเท้า radish", unit1: "หัว", unit2: "", usage: 0 },
        { id: "VEG01-N017-99-S03", name: "พริกแดง", searchKey: "พริกแดง red chili", unit1: "กก.", unit2: "ขีด", usage: 0 },
        { id: "VEG01-N018-99-S03", name: "กระเทียม", searchKey: "กระเทียม garlic", unit1: "กก.", unit2: "ขีด", usage: 0 },
        { id: "VEG01-N019-99-S03", name: "เห็ดเข็มทอง", searchKey: "เห็ดเข็มทอง enoki mushroom", unit1: "กก.", unit2: "ขีด", usage: 0 },
        { id: "VEG01-N020-99-S03", name: "เห็ดออรินจิ", searchKey: "เห็ดออรินจิ eringi mushroom", unit1: "กก.", unit2: "ขีด", usage: 0 },
        { id: "VEG01-N021-99-S03", name: "กระเจี๊ยบ", searchKey: "กระเจี๊ยบ okra", unit1: "กก.", unit2: "ขีด", usage: 0 },
        { id: "VEG01-N022-99-S03", name: "มะเขือเทศ", searchKey: "มะเขือเทศ tomato", unit1: "กก.", unit2: "ขีด", usage: 0 },
        { id: "VEG01-N023-99-S03", name: "มะนาว", searchKey: "มะนาว lime", unit1: "กก.", unit2: "ขีด", usage: 0 },
        { id: "VEG01-N024-66-S03", name: "น้ำมะนาว", searchKey: "น้ำมะนาว lime juice", unit1: "ขวด", unit2: "", usage: 0 },
        { id: "VEG01-N025-33-S03", name: "ฟักทอง", searchKey: "ฟักทอง pumpkin", unit1: "หัว", unit2: "", usage: 0 },
        { id: "VEG01-N026-99-S03", name: "หอมใหญ่", searchKey: "หอมใหญ่ onion", unit1: "กก.", unit2: "ขีด", usage: 0 },
        { id: "VEG01-N027-99-S03", name: "หอมแขกแดง", searchKey: "หอมแขกแดง shallot", unit1: "กก.", unit2: "ขีด", usage: 0 },
        { id: "VEG01-N028-99-S03", name: "มันฝรั่ง", searchKey: "มันฝรั่ง potato", unit1: "กก.", unit2: "ขีด", usage: 0 },
        { id: "VEG01-N029-99-S03", name: "ขิงแก่", searchKey: "ขิงแก่ old ginger", unit1: "กก.", unit2: "ขีด", usage: 0 },
        { id: "VEG01-N030-77-S04", name: "ถั่วแระญี่ปุ่น", searchKey: "ถั่วแระญี่ปุ่น edamame", unit1: "แพ็ค", unit2: "", usage: 0 },
        { id: "VEG01-N031-99-S04", name: "กิมจิ", searchKey: "กิมจิ kimchi", unit1: "กก.", unit2: "ขีด", usage: 0 }
      ],
      "ของแห้ง เครื่องปรุง ข้าว (DRY01)": [
        { id: "DRY01-N001-77-S01", name: "สาหร่ายแผ่น", searchKey: "สาหร่ายแผ่น seaweed sheet", unit1: "แพ็ค", unit2: "", usage: 0 },
        { id: "DRY01-N002-66-S01", name: "น้ำมันงา", searchKey: "น้ำมันงา sesame oil", unit1: "ขวด", unit2: "", usage: 0 },
        { id: "DRY01-N003-66-S01", name: "น้ำมันพริก layu", searchKey: "น้ำมันพริก layu chili oil", unit1: "ขวด", unit2: "", usage: 0 },
        { id: "DRY01-N004-55-S01", name: "ผงดาชิ", searchKey: "ผงดาชิ dashi powder", unit1: "ถุง", unit2: "", usage: 0 },
        { id: "DRY01-N005-55-S01", name: "ผงกระเทียม", searchKey: "ผงกระเทียม garlic powder", unit1: "ถุง", unit2: "", usage: 0 },
        { id: "DRY01-N006-55-S01", name: "พริกไทยผง", searchKey: "พริกไทยผง pepper powder", unit1: "ถุง", unit2: "", usage: 0 },
        { id: "DRY01-N007-55-S01", name: "ซอสพริก", searchKey: "ซอสพริก chili sauce", unit1: "ถุง", unit2: "", usage: 0 },
        { id: "DRY01-N008-66-S01", name: "ซีอิ๊วขาว", searchKey: "ซีอิ๊วขาว soy sauce", unit1: "ขวด", unit2: "", usage: 0 },
        { id: "DRY01-N009-66-S01", name: "น้ำส้มสายชู", searchKey: "น้ำส้มสายชู vinegar", unit1: "ขวด", unit2: "", usage: 0 },
        { id: "DRY01-N010-77-S01", name: "ผงมะนาว", searchKey: "ผงมะนาว lime powder", unit1: "แพ็ค", unit2: "", usage: 0 },
        { id: "DRY01-N011-77-S01", name: "น้ำตาลทรายแดง", searchKey: "น้ำตาลทรายแดง brown sugar", unit1: "แพ็ค", unit2: "", usage: 0 },
        { id: "DRY01-N012-77-S01", name: "น้ำตาลปี๊บ", searchKey: "น้ำตาลปี๊บ palm sugar", unit1: "แพ็ค", unit2: "", usage: 0 },
        { id: "DRY01-N013-77-S01", name: "แป้งสาลี", searchKey: "แป้งสาลี wheat flour", unit1: "แพ็ค", unit2: "", usage: 0 },
        { id: "DRY01-N014-77-S01", name: "แป้งทอดกรอบ", searchKey: "แป้งทอดกรอบ tempura flour", unit1: "แพ็ค", unit2: "", usage: 0 },
        { id: "DRY01-N015-77-S01", name: "แป้งมัน", searchKey: "แป้งมัน tapioca starch", unit1: "แพ็ค", unit2: "", usage: 0 },
        { id: "DRY01-N016-77-S01", name: "แป้งข้าวโพด", searchKey: "แป้งข้าวโพด corn starch", unit1: "แพ็ค", unit2: "", usage: 0 },
        { id: "DRY01-N017-77-S01", name: "แป้งโกกิ", searchKey: "แป้งโกกิ gogi flour", unit1: "แพ็ค", unit2: "", usage: 0 },
        { id: "DRY01-N018-77-S01", name: "เกลือปรุงรส", searchKey: "เกลือปรุงรส salt", unit1: "แพ็ค", unit2: "", usage: 0 },
        { id: "DRY01-N019-77-S01", name: "เกลือเม็ด", searchKey: "เกลือเม็ด rock salt", unit1: "แพ็ค", unit2: "", usage: 0 },
        { id: "DRY01-N020-77-S01", name: "ผงชูรส", searchKey: "ผงชูรส msg", unit1: "แพ็ค", unit2: "", usage: 0 },
        { id: "DRY01-N021-77-S01", name: "รสดีไก่", searchKey: "รสดีไก่ chicken powder", unit1: "แพ็ค", unit2: "", usage: 0 },
        { id: "DRY01-N022-66-S01", name: "คนอร์", searchKey: "คนอร์ knorr cube", unit1: "กล่อง", unit2: "", usage: 0 },
        { id: "DRY01-N023-55-S01", name: "ข้าวหอมมะลิ", searchKey: "ข้าวหอมมะลิ jasmine rice", unit1: "กระสอบ", unit2: "", usage: 0 },
        { id: "DRY01-N024-55-S01", name: "แป้งเกี๊ยวซ่า", searchKey: "แป้งเกี๊ยวซ่า gyoza flour", unit1: "ถุง", unit2: "", usage: 0 },
        { id: "DRY01-N025-77-S01", name: "โอโคโนมิยากิ ซอส", searchKey: "โอโคโนมิยากิ ซอส okonomiyaki sauce", unit1: "แพ็ค", unit2: "", usage: 0 },
        { id: "DRY01-N026-66-S01", name: "น้ำมันพืช", searchKey: "น้ำมันพืช vegetable oil", unit1: "ปี๊บ", unit2: "", usage: 0 },
        { id: "DRY01-N027-77-S01", name: "นมข้นจืดทีพอท", searchKey: "นมข้นจืดทีพอท evaporated milk", unit1: "แพ็ค", unit2: "", usage: 0 },
        { id: "DRY01-N028-66-S01", name: "ชิโรดาชิ", searchKey: "ชิโรดาชิ shiro dashi", unit1: "ขวด", unit2: "", usage: 0 },
        { id: "DRY01-N029-77-S01", name: "น้ำมะขามเปียก", searchKey: "น้ำมะขามเปียก tamarind paste", unit1: "แพ็ค", unit2: "", usage: 0 },
        { id: "DRY01-N030-66-S01", name: "น้ำปลาทิพรส", searchKey: "น้ำปลาทิพรส fish sauce", unit1: "แกลลอน", unit2: "", usage: 0 },
        { id: "DRY01-N031-77-S01", name: "งาขาว", searchKey: "งาขาว white sesame", unit1: "แพ็ค", unit2: "", usage: 0 },
        { id: "DRY01-N032-66-S04", name: "สาเก", searchKey: "สาเก sake", unit1: "ลัง", unit2: "", usage: 0 },
        { id: "DRY01-N033-66-S04", name: "มิริน", searchKey: "มิริน mirin", unit1: "ลัง", unit2: "", usage: 0 },
        { id: "DRY01-N034-66-S04", name: "โชยุคิโคเมน", searchKey: "โชยุคิโคเมน shoyu", unit1: "แกลลอน", unit2: "", usage: 0 },
        { id: "DRY01-N035-77-S04", name: "คัสสึโอะ", searchKey: "คัสสึโอะ bonito flakes", unit1: "แพ็ค", unit2: "", usage: 0 },
        { id: "DRY01-N036-77-S04", name: "มายองเนสคิวพี", searchKey: "มายองเนสคิวพี kewpie mayo", unit1: "แพ็ค", unit2: "", usage: 0 },
        { id: "DRY01-N037-55-S04", name: "มิโซะ", searchKey: "มิโซะ miso", unit1: "ถุง", unit2: "", usage: 0 },
        { id: "DRY01-N038-99-S04", name: "ข้าวญี่ปุ่น", searchKey: "ข้าวญี่ปุ่น japanese rice", unit1: "กก.", unit2: "ขีด", usage: 0 },
        { id: "DRY01-N039-77-S04", name: "สาหร่ายห่อข้าว", searchKey: "สาหร่ายห่อข้าว seaweed wrap", unit1: "แพ็ค", unit2: "", usage: 0 },
        { id: "DRY01-N040-77-S04", name: "เนย", searchKey: "เนย butter", unit1: "แพ็ค", unit2: "", usage: 0 },
        { id: "DRY01-N041-66-S04", name: "ลายุ/น้ำมันพริก", searchKey: "ลายุ น้ำมันพริก rayu", unit1: "ขวด", unit2: "", usage: 0 },
        { id: "DRY01-N042-66-S04", name: "พอนซึ", searchKey: "พอนซึ ponzu", unit1: "ขวด", unit2: "", usage: 0 },
        { id: "DRY01-N043-55-S04", name: "เกล็ดขนมปัง", searchKey: "เกล็ดขนมปัง breadcrumbs", unit1: "ถุง", unit2: "", usage: 0 },
        { id: "DRY01-N044-55-S04", name: "ปลาโอแผ่นใหญ่", searchKey: "ปลาโอแผ่นใหญ่ bonito large", unit1: "ถุง", unit2: "", usage: 0 },
        { id: "DRY01-N045-66-S04", name: "วูสเตอร์ซอส", searchKey: "วูสเตอร์ซอส worcester sauce", unit1: "ขวด", unit2: "", usage: 0 }
      ],
      "ของใช้และบรรจุภัณฑ์ (SUP01)": [
        { id: "SUP01-N001-77-S01", name: "หลอดหักงอ", searchKey: "หลอดหักงอ straw", unit1: "แพ็ค", unit2: "", usage: 0 },
        { id: "SUP01-N002-77-S01", name: "แอลกอฮอล์", searchKey: "แอลกอฮอล์ alcohol", unit1: "แพ็ค", unit2: "", usage: 0 },
        { id: "SUP01-N003-77-S01", name: "ทิชชู่ม้วนใหญ่", searchKey: "ทิชชู่ม้วนใหญ่ tissue large", unit1: "แพ็ค", unit2: "", usage: 0 },
        { id: "SUP01-N004-77-S01", name: "ทิชชู่ลูกค้า", searchKey: "ทิชชู่ลูกค้า napkin", unit1: "แพ็ค", unit2: "", usage: 0 },
        { id: "SUP01-N005-77-S01", name: "ตะเกียบ", searchKey: "ตะเกียบ chopsticks", unit1: "แพ็ค", unit2: "", usage: 0 },
        { id: "SUP01-N006-66-S01", name: "น้ำยาล้างจาน", searchKey: "น้ำยาล้างจาน dish soap", unit1: "แกลลอน", unit2: "", usage: 0 },
        { id: "SUP01-N007-77-S03", name: "ถุงขยะ 30*40", searchKey: "ถุงขยะ garbage bag", unit1: "แพ็ค", unit2: "", usage: 0 },
        { id: "SUP01-N008-77-S03", name: "ถุงขุ่น 6*8", searchKey: "ถุงขุ่น cloudy bag", unit1: "แพ็ค", unit2: "", usage: 0 },
        { id: "SUP01-N009-77-S03", name: "ถุงขุ่น 10*15", searchKey: "ถุงขุ่น cloudy bag", unit1: "แพ็ค", unit2: "", usage: 0 },
        { id: "SUP01-N010-77-S03", name: "ไม้เสียบ 7นิ้ว", searchKey: "ไม้เสียบ skewers", unit1: "แพ็ค", unit2: "", usage: 0 },
        { id: "SUP01-N011-77-S03", name: "ถุงหูหิ้ว", searchKey: "ถุงหูหิ้ว carrier bag", unit1: "แพ็ค", unit2: "", usage: 0 }
      ]
    },
    
    // 🍸 โซนบาร์ (BAR)
    BAR: {
      "สุราและเหล้านอก (SPI01)": [
        { id: "SPI01-N001-66-S05", name: "รีเจนซี่ (Regency)", searchKey: "รีเจนซี่ regency", unit1: "ลัง", unit2: "ขวด", usage: 0 },
        { id: "SPI01-N002-66-S05", name: "เมาน์เทนคิง (Mountain King)", searchKey: "เมาน์เทนคิง mountain king", unit1: "ลัง", unit2: "ขวด", usage: 0 },
        { id: "SPI01-N003-66-S05", name: "ฮันนี่ คอนติ VSOP (Honney Conti VSOP)", searchKey: "ฮันนี่ คอนติ vsop honney conti", unit1: "ลัง", unit2: "ขวด", usage: 0 },
        { id: "SPI01-N004-66-S05", name: "ฮันนี่ คอนติ XO (Honney Conti XO)", searchKey: "ฮันนี่ คอนติ xo honney conti", unit1: "ลัง", unit2: "ขวด", usage: 0 },
        { id: "SPI01-N005-66-S05", name: "เฮนเนสซี่ VSOP (Hennessy VSOP)", searchKey: "เฮนเนสซี่ hennessy vsop", unit1: "ขวด", unit2: "", usage: 0 },
        { id: "SPI01-N006-66-S05", name: "เฮนเนสซี่ คอนญัก (Hennessy Cognac)", searchKey: "เฮนเนสซี่ คอนญัก hennessy cognac", unit1: "ขวด", unit2: "", usage: 0 },
        { id: "SPI01-N007-66-S05", name: "แบล็ค เลเบิ้ล (Black Label)", searchKey: "แบล็ค black label", unit1: "ลัง", unit2: "ขวด", usage: 0 },
        { id: "SPI01-N008-66-S05", name: "มังกี้ โชลเดอร์ (Monkey Shoulder)", searchKey: "มังกี้ monkey shoulder", unit1: "ขวด", unit2: "", usage: 0 },
        { id: "SPI01-N009-66-S05", name: "แจ็ค แดเนียลส์ เล็ก (Jack Daniels Small)", searchKey: "แจ็ค jack daniels small เล็ก", unit1: "ขวด", unit2: "", usage: 0 },
        { id: "SPI01-N010-66-S05", name: "แจ็ค แดเนียลส์ (Jack Daniels)", searchKey: "แจ็ค jack daniels", unit1: "ขวด", unit2: "", usage: 0 },
        { id: "SPI01-N011-66-S05", name: "แจ็ค แดเนียลส์ แอปเปิ้ล (Jack Daniels Apple)", searchKey: "แจ็ค แอปเปิ้ล jack daniels apple", unit1: "ขวด", unit2: "", usage: 0 }
      ],
      "เบียร์และไซเดอร์ (BEE01)": [
        { id: "BEE01-N001-22-S05", name: "อาซาฮี สด (Asahi Draft)", searchKey: "เบียร์สด อาซาฮี asahi draft", unit1: "ถัง", unit2: "", usage: 0 },
        { id: "BEE01-N002-66-S05", name: "เบียร์ช้าง คลาสสิก (Chang Classic)", searchKey: "ช้าง chang เบียร์ช้าง", unit1: "ลัง", unit2: "ขวด", usage: 0 },
        { id: "BEE01-N003-66-S05", name: "เบียร์ลีโอ (Leo Beer)", searchKey: "ลีโอ leo เบียร์ลีโอ", unit1: "ลัง", unit2: "ขวด", usage: 0 },
        { id: "BEE01-N004-66-S05", name: "เบียร์สิงห์ (Singha Beer)", searchKey: "สิงห์ singha เบียร์สิงห์", unit1: "ลัง", unit2: "ขวด", usage: 0 },
        { id: "BEE01-N005-44-S05", name: "คาราบาว ดุงเกล (Carabao Dunkel)", searchKey: "คาราบาว carabao dunkel ดุงเกล", unit1: "ถาด", unit2: "กระป๋อง", usage: 0 },
        { id: "BEE01-N006-44-S05", name: "คาราบาว ลาเกอร์ (Carabao Lager)", searchKey: "คาราบาว carabao lager ลาเกอร์", unit1: "ถาด", unit2: "กระป๋อง", usage: 0 },
        { id: "BEE01-N007-44-S05", name: "ตะวันแดง IPA (Tawandang IPA)", searchKey: "ตะวันแดง tawandang ipa", unit1: "ถาด", unit2: "กระป๋อง", usage: 0 },
        { id: "BEE01-N008-44-S05", name: "ตะวันแดง โรส (Tawandang Rose)", searchKey: "ตะวันแดง tawandang rose โรส", unit1: "ถาด", unit2: "กระป๋อง", usage: 0 },
        { id: "BEE01-N009-44-S05", name: "ตะวันแดง ไวเซ่น (Tawandang Weizen)", searchKey: "ตะวันแดง tawandang weizen ไวเซ่น", unit1: "ถาด", unit2: "กระป๋อง", usage: 0 },
        { id: "BEE01-N010-66-S05", name: "บัดไวเซอร์ (Budweiser)", searchKey: "บัดไวเซอร์ budweiser", unit1: "ลัง", unit2: "ขวด", usage: 0 },
        { id: "BEE01-N011-66-S05", name: "ซาน มิเกล (San Miguel Beer)", searchKey: "ซาน มิเกล san miguel", unit1: "ลัง", unit2: "ขวด", usage: 0 },
        { id: "BEE01-N012-66-S05", name: "ซาน มิเกล เพล พิลเซน (San Miguel Pale Pilsen)", searchKey: "ซาน มิเกล เพล พิลเซน san miguel pale pilsen", unit1: "ลัง", unit2: "ขวด", usage: 0 },
        { id: "BEE01-N013-66-S05", name: "ซาน มิเกล ไลท์ (San Mig Light)", searchKey: "ซาน มิเกล ไลท์ san mig light", unit1: "ลัง", unit2: "ขวด", usage: 0 },
        { id: "BEE01-N014-66-S05", name: "โฮการ์เด้น ไวท์ (Hoegaarden White)", searchKey: "โฮการ์เด้น ไวท์ hoegaarden white", unit1: "ลัง", unit2: "ขวด", usage: 0 },
        { id: "BEE01-N015-66-S05", name: "โฮการ์เด้น โรส (Hoegaarden Rose)", searchKey: "โฮการ์เด้น โรส hoegaarden rose", unit1: "ลัง", unit2: "ขวด", usage: 0 },
        { id: "BEE01-N016-66-S05", name: "มูส อินดี้ ซัมเมอร์ (Moose Indie Summer)", searchKey: "มูส อินดี้ moose indie summer", unit1: "ลัง", unit2: "ขวด", usage: 0 },
        { id: "BEE01-N017-66-S05", name: "มูส ออริจินัล (Moose Original)", searchKey: "มูส ออริจินัล moose original", unit1: "ลัง", unit2: "ขวด", usage: 0 }
      ],
      "สาเกและเหล้าบ๊วย (SAK01)": [
        { id: "SAK01-N001-66-S05", name: "คิวคิว ออริจินัล เล็ก (Kyu Kyu Original S)", searchKey: "คิวคิว kyu kyu", unit1: "ขวด", unit2: "", usage: 0 },
        { id: "SAK01-N002-66-S05", name: "คิวคิว ออริจินัล ใหญ่ (Kyu Kyu Original L)", searchKey: "คิวคิว ใหญ่ kyu kyu l", unit1: "ขวด", unit2: "", usage: 0 },
        { id: "SAK01-N003-66-S05", name: "คิวคิว ซีโร่ เล็ก (Kyu Kyu Zero Sugar S)", searchKey: "คิวคิว ซีโร่ kyu kyu zero", unit1: "ขวด", unit2: "", usage: 0 },
        { id: "SAK01-N004-66-S05", name: "คิวคิว ซีโร่ ใหญ่ (Kyu Kyu Zero Sugar L)", searchKey: "คิวคิว ซีโร่ ใหญ่ kyu kyu zero l", unit1: "ขวด", unit2: "", usage: 0 },
        { id: "SAK01-N005-66-S05", name: "คิวคิว ยูซุ เล็ก (Kyu Kyu Yuzu S)", searchKey: "คิวคิว ยูซุ kyu kyu yuzu", unit1: "ขวด", unit2: "", usage: 0 },
        { id: "SAK01-N006-66-S05", name: "คิวคิว ยูซุ ใหญ่ (Kyu Kyu Yuzu L)", searchKey: "คิวคิว ยูซุ ใหญ่ kyu kyu yuzu l", unit1: "ขวด", unit2: "", usage: 0 },
        { id: "SAK01-N007-66-S05", name: "คิวคิว ฮันนี่ (Kyu Kyu Honey)", searchKey: "คิวคิว ฮันนี่ kyu kyu honey", unit1: "ขวด", unit2: "", usage: 0 },
        { id: "SAK01-N008-66-S05", name: "โซระ (Sora Japanese Umeshu)", searchKey: "โซระ sora umeshu", unit1: "ขวด", unit2: "", usage: 0 },
        { id: "SAK01-N009-66-S05", name: "ฮาคุซูรุ สาเก กล่อง (Hakutsuru Sake Box)", searchKey: "ฮาคุซูรุ สาเก กล่อง hakutsuru sake box", unit1: "กล่อง", unit2: "", usage: 0 },
        { id: "SAK01-N010-66-S05", name: "ฮาคุซูรุ ซายูริ (Hakutsuru Sayuri Nigori)", searchKey: "ฮาคุซูรุ ซายูริ hakutsuru sayuri", unit1: "ขวด", unit2: "", usage: 0 },
        { id: "SAK01-N011-66-S05", name: "ฮาคุซูรุ นามะ (Hakutsuru Nama Sake)", searchKey: "ฮาคุซูรุ นามะ hakutsuru nama", unit1: "ขวด", unit2: "", usage: 0 },
        { id: "SAK01-N012-66-S05", name: "ฮาคุซูรุ จุนไม กินโจ (Hakutsuru Junmai Ginjo)", searchKey: "ฮาคุซูรุ จุนไม กินโจ hakutsuru junmai", unit1: "ขวด", unit2: "", usage: 0 },
        { id: "SAK01-N013-66-S05", name: "ฮาคุซูรุ ยูซุชุ (Hakutsuru Nigori Yuzushu)", searchKey: "ฮาคุซูรุ ยูซุชุ hakutsuru yuzushu", unit1: "ขวด", unit2: "", usage: 0 },
        { id: "SAK01-N014-66-S05", name: "อายะ เกรปฟรุต (Aya Sake Grapefruit)", searchKey: "อายะ เกรปฟรุต aya sake grapefruit", unit1: "ขวด", unit2: "", usage: 0 },
        { id: "SAK01-N015-66-S05", name: "อายะ พีช (Aya Sake Peach)", searchKey: "อายะ พีช aya sake peach", unit1: "ขวด", unit2: "", usage: 0 },
        { id: "SAK01-N016-66-S05", name: "อายะ ยูซุ (Aya Sake Yuzu)", searchKey: "อายะ ยูซุ aya sake yuzu", unit1: "ขวด", unit2: "", usage: 0 },
        { id: "SAK01-N017-44-S05", name: "ปุรุปุรุ พีช (Purupuru Jelly Peach)", searchKey: "ปุรุปุรุ พีช purupuru jelly peach", unit1: "กระป๋อง", unit2: "", usage: 0 },
        { id: "SAK01-N018-44-S05", name: "ปุรุปุรุ บ๊วย (Purupuru Jelly Umeshu)", searchKey: "ปุรุปุรุ บ๊วย purupuru jelly umeshu", unit1: "กระป๋อง", unit2: "", usage: 0 },
        { id: "SAK01-N019-44-S05", name: "ปุรุปุรุ แอปเปิ้ล (Purupuru Jelly Apple)", searchKey: "ปุรุปุรุ แอปเปิ้ล purupuru jelly apple", unit1: "กระป๋อง", unit2: "", usage: 0 },
        { id: "SAK01-N020-44-S05", name: "ปุรุปุรุ องุ่น (Purupuru Jelly Muscat)", searchKey: "ปุรุปุรุ องุ่น purupuru jelly muscat", unit1: "กระป๋อง", unit2: "", usage: 0 },
        { id: "SAK01-N021-66-S05", name: "เหล้าบ๊วย ขวดใหญ่ (Umeshu Big Bottle)", searchKey: "เหล้าบ๊วย ขวดใหญ่ umeshu big bottle", unit1: "ขวด", unit2: "", usage: 0 }
      ],
      "โซจู (SOJ01)": [
        { id: "SOJ01-N001-66-S05", name: "ซอนมูล ฮาร์ทมูน (Seonmul Heart Moon)", searchKey: "ซอนมูล ฮาร์ทมูน seonmul heart moon", unit1: "ลัง", unit2: "ขวด", usage: 0 },
        { id: "SOJ01-N002-66-S05", name: "ซอนมูล องุ่นเขียว (Seonmul Green Grape)", searchKey: "ซอนมูล องุ่นเขียว seonmul green grape", unit1: "ลัง", unit2: "ขวด", usage: 0 },
        { id: "SOJ01-N003-66-S05", name: "ซอนมูล เกรปฟรุต (Seonmul Grapefruit)", searchKey: "ซอนมูล เกรปฟรุต seonmul grapefruit", unit1: "ลัง", unit2: "ขวด", usage: 0 },
        { id: "SOJ01-N004-66-S05", name: "ซอนมูล สตรอว์เบอร์รี่ (Seonmul Strawberry)", searchKey: "ซอนมูล สตรอว์เบอร์รี่ seonmul strawberry", unit1: "ลัง", unit2: "ขวด", usage: 0 },
        { id: "SOJ01-N005-66-S05", name: "ซอนมูล มิกซ์เบอร์รี่ (Seonmul Mixed Berry)", searchKey: "ซอนมูล มิกซ์เบอร์รี่ seonmul mixed berry", unit1: "ลัง", unit2: "ขวด", usage: 0 },
        { id: "SOJ01-N006-66-S05", name: "ซอนมูล โยเกิร์ต (Seonmul Yogurt)", searchKey: "ซอนมูล โยเกิร์ต seonmul yogurt", unit1: "ลัง", unit2: "ขวด", usage: 0 },
        { id: "SOJ01-N007-66-S05", name: "ซอนมูล บลูเบอรี่ (Seonmul Blueberry)", searchKey: "ซอนมูล บลูเบอรี่ seonmul blueberry", unit1: "ลัง", unit2: "ขวด", usage: 0 },
        { id: "SOJ01-N008-66-S05", name: "ซอนมูล พีช (Seonmul Peach)", searchKey: "ซอนมูล พีช seonmul peach", unit1: "ลัง", unit2: "ขวด", usage: 0 },
        { id: "SOJ01-N009-66-S05", name: "ซอนมูล แอปเปิ้ล (Seonmul Apple)", searchKey: "ซอนมูล แอปเปิ้ล seonmul apple", unit1: "ลัง", unit2: "ขวด", usage: 0 },
        { id: "SOJ01-N010-66-S05", name: "ซอนมูล ใบกัญชา (Seonmul Cannabis Leaf)", searchKey: "ซอนมูล ใบกัญชา seonmul cannabis", unit1: "ลัง", unit2: "ขวด", usage: 0 },
        { id: "SOJ01-N011-66-S05", name: "ซอนมูล ส้ม (Seonmul Orange)", searchKey: "ซอนมูล ส้ม seonmul orange", unit1: "ลัง", unit2: "ขวด", usage: 0 },
        { id: "SOJ01-N012-66-S05", name: "ซอนมูล ลิ้นจี่ (Seonmul Lychee)", searchKey: "ซอนมูล ลิ้นจี่ seonmul lychee", unit1: "ลัง", unit2: "ขวด", usage: 0 },
        { id: "SOJ01-N013-66-S05", name: "ซอนมูล แอพริคอต (Seonmul Apricot)", searchKey: "ซอนมูล แอพริคอต seonmul apricot", unit1: "ลัง", unit2: "ขวด", usage: 0 }
      ],
      "ไวน์ (WIN01)": [
        { id: "WIN01-N001-66-S05", name: "โรเบิร์ต มอนดาวี (Robert Mondavi Select)", searchKey: "โรเบิร์ต มอนดาวี robert mondavi", unit1: "ขวด", unit2: "", usage: 0 },
        { id: "WIN01-N002-66-S05", name: "ซานต้า เฮเลน่า แดง (Santa Helena Cab Sau)", searchKey: "ซานต้า เฮเลน่า แดง santa helena", unit1: "ขวด", unit2: "", usage: 0 },
        { id: "WIN01-N003-66-S05", name: "ซานต้า เฮเลน่า ขาว (Santa Helena Gran Vino)", searchKey: "ซานต้า เฮเลน่า ขาว santa helena", unit1: "ขวด", unit2: "", usage: 0 },
        { id: "WIN01-N004-66-S05", name: "โทโร่ โดโร่ (Toro D'oro Selection)", searchKey: "โทโร่ โดโร่ toro d'oro", unit1: "ขวด", unit2: "", usage: 0 },
        { id: "WIN01-N005-66-S05", name: "เจคอบส์ ครีก โรส (Jacobs Creek Rose)", searchKey: "เจคอบส์ ครีก โรส jacobs creek rose", unit1: "ขวด", unit2: "", usage: 0 }
      ],
      "ค็อกเทล (COC01)": [
        { id: "COC01-N001-66-S05", name: "เฮ้าส์ บลู มาร์การิต้า (Haus Blue Margarita)", searchKey: "เฮ้าส์ บลู มาร์การิต้า haus blue margarita", unit1: "แก้ว", unit2: "", usage: 0 },
        { id: "COC01-N002-66-S05", name: "เฮ้าส์ โมฮิโต้ (Haus Mojito)", searchKey: "เฮ้าส์ โมฮิโต้ haus mojito", unit1: "แก้ว", unit2: "", usage: 0 },
        { id: "COC01-N003-66-S05", name: "เฮ้าส์ พันช์ (Haus Punch)", searchKey: "เฮ้าส์ พันช์ haus punch", unit1: "แก้ว", unit2: "", usage: 0 },
        { id: "COC01-N004-66-S05", name: "เฮ้าส์ โอลด์ แฟชั่น (Haus Old Fashion)", searchKey: "เฮ้าส์ โอลด์ แฟชั่น haus old fashion", unit1: "แก้ว", unit2: "", usage: 0 }
      ],
      "น้ำอัดลมและมิกเซอร์ (SOF01)": [
        { id: "SOF01-N001-66-S05", name: "น้ำดื่ม (Water)", searchKey: "น้ำดื่ม water", unit1: "แพ็ค", unit2: "ขวด", usage: 0 },
        { id: "SOF01-N002-66-S05", name: "โซดา (Soda Water)", searchKey: "โซดา soda water", unit1: "ถาด", unit2: "ขวด", usage: 0 },
        { id: "SOF01-N003-44-S05", name: "โค้ก (Coke Original)", searchKey: "โค้ก coke", unit1: "ถาด", unit2: "กระป๋อง", usage: 0 },
        { id: "SOF01-N004-44-S05", name: "โค้ก ไม่มีน้ำตาล (Coke Zero)", searchKey: "โค้กซีโร่ coke zero", unit1: "ถาด", unit2: "กระป๋อง", usage: 0 },
        { id: "SOF01-N005-44-S05", name: "สไปร์ท (Sprite)", searchKey: "สไปร์ท sprite", unit1: "ถาด", unit2: "กระป๋อง", usage: 0 },
        { id: "SOF01-N006-44-S05", name: "แฟนต้า น้ำเขียว (Fanta Green)", searchKey: "น้ำเขียว แฟนต้า fanta green", unit1: "ถาด", unit2: "กระป๋อง", usage: 0 },
        { id: "SOF01-N007-44-S05", name: "แฟนต้า น้ำแดง (Fanta Red)", searchKey: "น้ำแดง แฟนต้า fanta red", unit1: "ถาด", unit2: "กระป๋อง", usage: 0 },
        { id: "SOF01-N008-44-S05", name: "แฟนต้า น้ำส้ม (Fanta Orange)", searchKey: "น้ำส้ม แฟนต้า fanta orange", unit1: "ถาด", unit2: "กระป๋อง", usage: 0 },
        { id: "SOF01-N009-44-S05", name: "เลมอน โซดา (Lemon Soda)", searchKey: "เลมอน โซดา lemon soda", unit1: "ถาด", unit2: "กระป๋อง", usage: 0 },
        { id: "SOF01-N010-44-S05", name: "ชเวปส์ มะนาวโซดา (Schweppes Lime Soda)", searchKey: "ชเวปส์ มะนาวโซดา schweppes lime soda", unit1: "ถาด", unit2: "กระป๋อง", usage: 0 },
        { id: "SOF01-N011-66-S05", name: "โออิชิ ต้นตำรับ (Oishi Original)", searchKey: "โออิชิ ต้นตำรับ oishi original", unit1: "แพ็ค", unit2: "ขวด", usage: 0 },
        { id: "SOF01-N012-66-S05", name: "โออิชิ น้ำผึ้งมะนาว (Oishi Honey Lemon)", searchKey: "โออิชิ น้ำผึ้งมะนาว oishi honey lemon", unit1: "แพ็ค", unit2: "ขวด", usage: 0 }
      ]
    }
  };